apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    release: {{ .Release.Name }}
data:
  default.conf: |-
    server {
      listen      80;
      server_name {{ join " " .Values.ingress.hosts }};

      # Rails

      location / {
        proxy_pass       http://localhost:3000;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
        proxy_set_header X-Forwarded-Ssl   on;
        
        # Increase header size for /switch_account/
        proxy_buffers           8 16k;
        proxy_buffer_size       16k;
        proxy_busy_buffers_size 16k;
      }

      # Analytics

      location /analytics/ {
        proxy_pass       https://{{ .Values.app.proxyHost }}/analytics/;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
        proxy_set_header X-Forwarded-Ssl   on;
      }

      # SPA

      location /spa/ {
        proxy_pass       https://{{ .Values.app.proxyHost }}/spa/;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
        proxy_set_header X-Forwarded-Ssl   on;
      }

      proxy_redirect https://$host/users/sign_in https://$host/spa/#/auth/login;
    }

    server {
      listen      8080;
      server_name {{ join " " .Values.ingress.hosts }};

      # NGINX Status

      location /nginx_status {
        stub_status on;
        access_log  off;
      }
    }
