apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    release: {{ .Release.Name }}
data:
  default: |-
    upstream puma {
      server unix:/var/run/puma.sock;
    }
    
    server {
      listen 80 default_server;
      server_name _;
    
      root /app/public;
    
      location / {
        try_files $uri @puma;
      }
    
      location /assets/ {
        gzip_static on;
        expires     max;
        add_header  Cache-Control public;
      }
    
      location @puma {
        proxy_pass       http://puma;
        proxy_set_header Host            $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # Required for Account Chooser
        proxy_buffers           8 16k;
        proxy_buffer_size       16k;
        proxy_busy_buffers_size 16k;
      }

{{ .Values.app.nginxConfig | indent 6 }}
    }
