apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "app.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/secrets: "{{ .Values.app.secretsChecksum }}"
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
{{- if .Values.datadog.enabled }}
        ad.datadoghq.com/rails.logs: >-
          [{
            "source": "ruby",
            "service": "{{ template "app.name" . }}"
          },
          {
            "source": "nginx",
            "service": "{{ template "app.name" . }}"
          }]
{{- end }}
{{- if .Values.app.podAnnotations }}
{{ toYaml .Values.app.podAnnotations | indent 8 }}
{{- end }}
      labels:
        app: {{ template "app.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: rails
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        envFrom:
        - secretRef:
            name: {{ template "app.name" . }}
        ports:
        - containerPort: 80
          name: http
{{- if .Values.app.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.app.livenessProbe | indent 10 }}
{{- end }}
{{- if .Values.app.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.app.readinessProbe | indent 10 }}
{{- end }}
{{- if .Values.app.resources }}
        resources:
{{ toYaml .Values.app.resources | indent 10 }}
{{- end }}
        volumeMounts:
          - name: confd
            mountPath: /etc/nginx/sites-enabled/
            readOnly: true
      volumes:
        - name: confd
          configMap:
            name: {{ template "app.fullname" . }}
