apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    release: {{ .Release.Name }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: {{ template "app.fullname" . }}
    release: {{ .Release.Name }}
