{{- if .Values.ingress.enabled }}
{{- $serviceName := include "fullname" . }}
apiVersion: networking/v1beta1
kind: Ingress
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
{{- range $host := .Values.ingress.hosts }}
  - host: {{ $host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $serviceName }}
          servicePort: http
{{- end }}
  tls:
  - hosts:
{{- range $host := .Values.ingress.hosts }}
    - {{ $host }}
{{- end }}
{{- end }}
