apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
{{- if .Values.app.maxUnavailable }}
  maxUnavailable: {{ .Values.app.maxUnavailable }}
{{- end }}
{{- if .Values.app.minAvailable }}
  minAvailable: {{ .Values.app.minAvailable }}
{{- end }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      release: {{ .Release.Name }}
